Update phpunit_dist.xml
YouweGit/testing-suite pull request #8
Opened 2022-08-10 12:47 UTC by arnoudhgz

See  https://phpunit.readthedocs.io/en/9.5/configuration.html#the-coverage-element

2022-08-10 13:32 UTC, woutk88 commented on templates/files/default/phpunit_dist.xml
>      <filter>
@arnoudhgz The filter element should be removed as well, that element has been replaced by coverage.

2022-08-10 17:56 UTC, leonhelmus requested changes

2022-08-10 17:56 UTC, leonhelmus commented on templates/files/default/phpunit_dist.xml
>      <filter>
After i will approve as well :)

2022-08-16 07:27 UTC, leonhelmus approved these changes

2022-08-16 08:09 UTC, woutk88 approved these changes

2022-08-22 07:01 UTC, igorwulff approved these changes

2022-08-25 10:58 UTC, merged